from schemas.response.brand import BrandListModel
from schemas.response.mobile import RetrieveMobileModel
from schemas.response.mobile import CreateResponseMobileModel
from schemas.response.mobile import BaseGetMobileModel
from schemas.response.mobile import ListMobileModel
from schemas.response.user import UserListModel
from schemas.response.comment import BaseCommentModel
from schemas.response.comment import RetrieveCommentModel
from schemas.response.mobile_prop import MobilePropModel
