from schemas.request.user import RegisterModel
from schemas.request.user import LoginModel
from schemas.request.user import AddUserModel
from schemas.request.brand import BrandModel
from schemas.request.comment import CreateCommentModel
from schemas.request.like import LikeModel
from schemas.request.save import SaveModel
from schemas.request.mobile_prop import CreatePropModel
from schemas.request.mobile_prop import InputPropModel
from schemas.request.mobile_photo import MobilePhotoModel
from schemas.request.mobile import CreateMobileModel
from schemas.request.article import CreateArticleModel
