from managers.auth import AuthManager
from managers.auth import ProtectedHTTPBearer
from managers.auth import is_admin
from managers.auth import is_superuser
from managers.auth import is_observer
from managers.auth import oauth2_scheme
from managers.auth import is_authenticated
from managers.brand import BrandManager
from managers.mobile import MobileManager
from managers.user import UserManager
from managers.comment import CommentManager
from managers.mobile_prop import MobilePropManager
from managers.mobile_photo import MobilePhotoManager
from managers.like import LikeManager
from managers.save import SaveManager
from managers.article import ArticleManager
